apiVersion: v1
kind: Template
metadata:
  name: kstreams-service

parameters:
- name: NAMESPACE
  description: Name of your project (e.g. myproject)

objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: kstreams-service
    name: kstreams-service
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    selector:
      deploymentconfig: kstreams-service
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kstreams-service
          deploymentconfig: kstreams-service
      spec:
        containers:
        - image: ${NAMESPACE}/kstreams-service
          imagePullPolicy: Always
          name: kstreams-service
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - kstreams-service
        from:
          kind: ImageStreamTag
          name: kstreams-service:latest
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange
